### PR TITLE
Make it build with ghc-9.10

### PR DESCRIPTION
**Pull request by erikd**
# Description

Add your description here, if it fixes a particular issue please provide a [link](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword=) to the issue.

# Checklist

- [x] Commit sequence broadly makes sense
- [ ] Commits have useful messages
- [ ] New tests are added if needed and existing tests are updated
- [ ] Any changes are noted in the [changelog](https://github.com/IntersectMBO/cardano-db-sync/blob/master/db-sync/CHANGELOG.md)
- [ ] Code is formatted with [`fourmolu`](https://github.com/fourmolu/fourmolu) on version 0.10.1.0 (which can be run with `scripts/fourmolize.sh`)
- [ ] Self-reviewed the diff

# Migrations

- [ ] The pr causes a [breaking change](https://github.com/IntersectMBO/cardano-db-sync/blob/master/doc/migrations.md) of type a,b or c
- [ ] If there is a breaking change, the pr includes a database migration and/or a fix process for old values, so that upgrade is possible
- [ ] Resyncing and running the migrations provided will result in the same database semantically

If there is a breaking change, especially a big one, please add a justification here. Please elaborate
more what the migration achieves, what it cannot achieve or why a migration is not possible.

### CODE REVIEW

**Comment by erikd** [comment]
Tried to add `ghc-9.10` to the build matrix, but that version does not seem to exist in the support GHC versions with the way CI is set up.

**Comment by angerman** [comment]
Questions I have:
- Do we really need the shell? Can we just use the DevX shell? I guess @sgillespie might have an idea about this.
- Must we pin the cabal version? Or can we just go with `cabal = {}`?

**Comment by angerman** [comment]
As @hamishmack pointed out in #1873, @sgillespie bumped cabal. I think we should combine this and #1873? @sgillespie, @erikd what do you think?

**Comment by angerman** [comment]
Let me reiterate my point about the version:
> I'd rather just go with latest, that seems more robust.
> and _if_ we _must_ pin a version have a clear comment that states _why_ we pin the version.

**Comment by sgillespie** [comment]
Since adding GHC-9.10 to the GH action is ongoing, I'd like to go ahead and get this merged into master. We can add back the entry in the build matrix after we fix devx

**Review by sgillespie — APPROVED** [review]

**Pull request merged**
