### PR TITLE
Make it build with ghc-9.8

### PR DESCRIPTION
**Pull request by erikd**
# Description

Make it build with ghc-9.8

# Checklist

- [ ] Commit sequence broadly makes sense
- [ ] Commits have useful messages
- [ ] New tests are added if needed and existing tests are updated
- [ ] Any changes are noted in the [changelog](https://github.com/IntersectMBO/cardano-db-sync/blob/master/cardano-db-sync/CHANGELOG.md)
- [ ] Code is formatted with [`fourmolu`](https://github.com/fourmolu/fourmolu) on version 0.10.1.0 (which can be run with `scripts/fourmolize.sh`)
- [ ] Self-reviewed the diff

# Migrations

- [ ] The pr causes a [breaking change](https://github.com/IntersectMBO/cardano-db-sync/blob/master/doc/migrations.md) of type a,b or c
- [ ] If there is a breaking change, the pr includes a database migration and/or a fix process for old values, so that upgrade is possible
- [ ] Resyncing and running the migrations provided will result in the same database semantically

If there is a breaking change, especially a big one, please add a justification here. Please elaborate
more what the migration achieves, what it cannot achieve or why a migration is not possible.

### CODE REVIEW

**Review by sgillespie — APPROVED** [review]

**Review by Cmdv — APPROVED** [review]

**Review by Cmdv — CHANGES_REQUESTED** [review]
looks like it's now failing tests in the CI 😢 
This will need investigation as it's hard to know why `-Wno-x-partial` would cause incorrect functionality.

**Comment by erikd** [comment]
> This will need investigation as it's hard to know what `-Wno-x-partial` would cause incorrect functionality.

I can't see how  `-Wno-x-partial` could possibly cause changes in behavior. All it does is turn off a warning.

**Comment by Cmdv** [comment]
> I can't see how -Wno-x-partial could possibly cause changes in behaviour. All it does is turn off a warning.
unless the ghc98 CI is doing something different, I'm just trying to re run the tests now. It's compiling fine just the tests fail in various ways only on ghc98 but passes fine in ghc96 ghc810 (I'm not looking at the ci/hydra ones they always seem to fail). Hence something need to be investigated makes no sense the tests would all pass in other ghc versions 🤷

**Review by Cmdv — APPROVED** [review]

**Review by sgillespie — DISMISSED** [review]

**Review by sgillespie — APPROVED** [review]

**Comment by Cmdv** [comment]
🎉

**Pull request merged**
