### PR TITLE
1685 - expired epoch fix

### LINKED ISSUE #1685: retired epoch of gov_action_proposal is wrong
It's one epoch before it's actually retired. This should be fixed and the rollback should be adjusted.

### PR DESCRIPTION
**Pull request by Cmdv**
# Description

this fixes #1685 

The function adjusted is inserted on new epoch so will also work for rollbacks.

# Checklist

- [ ] Commit sequence broadly makes sense
- [ ] Commits have useful messages
- [ ] New tests are added if needed and existing tests are updated
- [ ] Any changes are noted in the [changelog](https://github.com/IntersectMBO/cardano-db-sync/blob/master/cardano-db-sync/CHANGELOG.md)
- [ ] Code is formatted with [`fourmolu`](https://github.com/fourmolu/fourmolu) on version 0.10.1.0 (which can be run with `scripts/fourmolize.sh`)
- [ ] Self-reviewed the diff

# Migrations

- [ ] The pr causes a [breaking change](https://github.com/IntersectMBO/cardano-db-sync/blob/master/doc/migrations.md) of type a,b or c
- [ ] If there is a breaking change, the pr includes a database migration and/or a fix process for old values, so that upgrade is possible
- [ ] Resyncing and running the migrations provided will result in the same database semantically

If there is a breaking change, especially a big one, please add a justification here. Please elaborate
more what the migration achieves, what it cannot achieve or why a migration is not possible.

### CODE REVIEW

**Comment by kderme** [comment]
@Cmdv does this work fine on sanchonet?

**Comment by Cmdv** [comment]
> @Cmdv does this work fine on sanchonet?

@kderme Does this look right?
SCR-20240516-jnt

**Comment by kderme** [comment]
What query produced the first one? In general I find text easier to read than screenshots. I would assume that dropped and expired epochs should match.

**Comment by Cmdv** [comment]
@kderme right this should have done the trick:

```
select id, dropped_epoch, expired_epoch, expiration from gov_action_proposal;

+----+---------------+---------------+------------+
| id | dropped_epoch | expired_epoch | expiration |
|----+---------------+---------------+------------|
| 5  | 311           | <null>        | 314        |
| 23 | 316           | 315           | 315        |
| 12 | 316           | 315           | 315        |
| 6  | 315           | 314           | 314        |
| 7  | 315           | 314           | 314        |
| 8  | 315           | 314           | 314        |
| 9  | 315           | 314           | 314        |
| 10 | 315           | 314           | 314        |
```

**Review by kderme — APPROVED** [review]

**Pull request merged**
